
#pragma once

///\b   GENERAL_CONFIGURATION
#define SIO_DEBUG_MODE false

///\b   UTILITY_CONFIGURATION
#define SIO_ASSERT_ENABLED false
#define SIO_WARN_ENABLED true

///\b   DMA_CONFIGURATION
#define SIO_DMA_CHANNELS 16
